export const pizzas = [
    {
        id: 1,
        name: "מרגריטה",
        description: "גבינת מוצרלה משובחת, רוטב עגבניות עשיר, בזיליקום טרי ושמן זית כתית מעולה. הקלאסיקה האיטלקית במיטבה.",
        price: 14.99,
        rating: 4.8,
        image: "/images/margherita.png",
        ingredients: ["רוטב עגבניות", "מוצרלה", "בזיליקום", "שמן זית"],
        calories: 850,
    },
    {
        id: 2,
        name: "פפרוני",
        description: "פרוסות פפרוני קריספיות, מוצרלה נמסה ורוטב עגבניות מתובל. שילוב מנצח של טעמים.",
        price: 16.99,
        rating: 4.9,
        image: "/images/pepperoni.png",
        ingredients: ["רוטב עגבניות", "מוצרלה", "פפרוני", "אורגנו"],
        calories: 1100,
    },
    {
        id: 3,
        name: "ירקות",
        description: "חגיגה של ירקות טריים: פלפלים צבעוניים, בצל סגול, פטריות, זיתים ועגבניות שרי על מצע של גבינת מוצרלה.",
        price: 15.99,
        rating: 4.7,
        image: "/images/veggie.png",
        ingredients: ["רוטב עגבניות", "מוצרלה", "פלפלים", "בצל", "פטריות", "זיתים"],
        calories: 750,
    },
    {
        id: 4,
        name: "מיוחדת כמהין",
        description: "רוטב שמנת כמהין עשיר, מיקס פטריות יער, פרמז'ן ונגיעות שמן כמהין. חוויה קולינרית יוקרתית.",
        price: 22.99,
        rating: 4.9,
        image: "/images/special.png",
        ingredients: ["רוטב שמנת כמהין", "מוצרלה", "פרמז'ן", "פטריות יער", "שמן כמהין"],
        calories: 950,
    },
    {
        id: 5,
        name: "יוונית",
        description: "גבינת פטה, זיתי קלמטה, בצל סגול, עגבניות ואורגנו. טעם של חופשה בים התיכון.",
        price: 17.50,
        rating: 4.6,
        image: "/images/veggie.png", // Fallback to veggie.png since greek.png missing
        ingredients: ["רוטב עגבניות", "מוצרלה", "גבינת פטה", "זיתי קלמטה", "בצל", "אורגנו"],
        calories: 880,
    },
    {
        id: 6,
        name: "הוואי",
        description: "השילוב השנוי במחלוקת אך האהוב: אננס מתוק ונקניק אווז, על בסיס רוטב עגבניות ומוצרלה.",
        price: 16.50,
        rating: 4.5,
        image: "/images/margherita.png", // Fallback to margherita.png since hawaiian.png missing
        ingredients: ["רוטב עגבניות", "מוצרלה", "אננס", "נקניק אווז"],
        calories: 920,
    },
]
